### PR TITLE
Contribution guidelines

### LINKED ISSUE #9: Contribution Guidelines
We should have contribution guidelines. Especially with regards to the process for getting code merged into master.

### PR DESCRIPTION
**Pull request by kylestach**
Closes #9.

This is a set of contribution guidelines that details the process for contributing to this project.

### CODE REVIEW

**Comment by WesleyAC** [comment]
Looks good!

I do have one question about the aim of the project, which is may be good to address in this PR: How similar are we attempting to make the API to the official WPILib API? I know that we're aiming for feature parity - are we also attempting to match APIs? Class names? What about merging classes that implement some, but not all of the features in the C++/Java WPILib project? Additionally, are we going to have things like PID controllers in this, that are in WPILib, but perhaps actually belong in a separate project?

Anyway, all the stuff in this looks good, I just though that this would be a good opportunity to raise this question.

**Comment by kylestach** [comment]
@WesleyAC this project should have feature parity with WPILib, but it won't be the exactly the same API wise. It's also going to (probably, we're still discussing this) be a lot more distributed than WPILib is - that is, controls stuff, etc. will be in separate crates. This repository will likely just serve as the hardware part of WPILib, pretty much as a nice Rust wrapper over the HAL.

I'll write that into a "Project Goals" section.

**Review by WesleyAC — APPROVED** [review]
LGTM 🚀 

I'll let you merge.

**Comment by kylestach** [comment]
@WesleyAC actually this brings up a point that should probably be addressed in CONTRIBUTING.md somewhere: are we going to use merge, rebase, or squash?

**Pull request merged**
